services:
  localstack:
    image: localstack/localstack
    networks:
      - app-network
    ports:
      - "4566:4566"
    environment:
      - SERVICES=secretsmanager
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  postgres:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - localstack
      - postgres
      - mock-api
    networks:
      - app-network
    ports:
      - "8080:8000"
    volumes:
      - ./volume/model_results:/data/model_results
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  mock-api:
    build:
      context: .
      dockerfile: Dockerfile.mock-api
    networks:
      - app-network
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    networks:
      - app-network
    ports:
      - "6379:6379"
    
  celery-worker:
    build: .
    depends_on:
      - app
      - redis
    networks:
      - app-network
    command: celery -A src.modtrack.celery_app:celery_app worker --loglevel=INFO
    volumes:
      - ./volume/model_results:/data/model_results
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - ENVIRONMENT=local

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: