[project]
name = "modtrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3==1.35.87",
    "schedule==1.2.2",
    "watchdog==6.0.0",
    "psycopg2-binary==2.9.9",  # Specify exact version
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"